// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNfhLU0mpEP7zpGiZEMpw1AQ3nPqYRneA',
    appId: '1:608851343966:web:813ec369c7c9a55b6ed2cf',
    messagingSenderId: '608851343966',
    projectId: 'ecommerceapp-baa4e',
    authDomain: 'ecommerceapp-baa4e.firebaseapp.com',
    storageBucket: 'ecommerceapp-baa4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8w6xbndvUPv5rcFRVZGfHfk8a4Hp-_ic',
    appId: '1:608851343966:android:4e4941f9da799f566ed2cf',
    messagingSenderId: '608851343966',
    projectId: 'ecommerceapp-baa4e',
    storageBucket: 'ecommerceapp-baa4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTfEagMrHXwfRIX37-SRhm6gYaVMTziFg',
    appId: '1:608851343966:ios:944d13b49e5580ef6ed2cf',
    messagingSenderId: '608851343966',
    projectId: 'ecommerceapp-baa4e',
    storageBucket: 'ecommerceapp-baa4e.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTfEagMrHXwfRIX37-SRhm6gYaVMTziFg',
    appId: '1:608851343966:ios:944d13b49e5580ef6ed2cf',
    messagingSenderId: '608851343966',
    projectId: 'ecommerceapp-baa4e',
    storageBucket: 'ecommerceapp-baa4e.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNfhLU0mpEP7zpGiZEMpw1AQ3nPqYRneA',
    appId: '1:608851343966:web:a4f52610449afc7f6ed2cf',
    messagingSenderId: '608851343966',
    projectId: 'ecommerceapp-baa4e',
    authDomain: 'ecommerceapp-baa4e.firebaseapp.com',
    storageBucket: 'ecommerceapp-baa4e.appspot.com',
  );
}
